"""Terminal output and markdown export using Rich."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.rule import Rule
from rich.text import Text

from gar.reviewer import ReviewResult

console = Console()


def print_header(title: str = "git-ai-review") -> None:
    console.print(Rule(f"[bold cyan]{title}[/bold cyan]"))


def print_review(result: ReviewResult) -> None:
    """Print a single file review as a Rich panel."""
    if result.error:
        console.print(
            Panel(
                Text(f"[error] {result.error}", style="red"),
                title=f"[bold red]{result.path}[/bold red]",
                border_style="red",
            )
        )
        return

    md = Markdown(result.review)
    console.print(
        Panel(
            md,
            title=f"[bold green]{result.path}[/bold green]",
            border_style="green",
            padding=(1, 2),
        )
    )


def print_all_reviews(results: list[ReviewResult]) -> None:
    print_header()
    console.print(f"[dim]{len(results)} file(s) reviewed[/dim]\n")
    for result in results:
        print_review(result)
        console.print()

    failed = [r for r in results if not r.ok]
    if failed:
        console.print(Rule("[bold red]Failed Reviews[/bold red]"))
        for r in failed:
            console.print(f"[red]✗ {r.path}:[/red] {r.error}")


def save_markdown(results: list[ReviewResult], output_path: Path | None = None) -> Path:
    """Save review results to a markdown file."""
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = Path(f"review_{timestamp}.md")

    lines: list[str] = [
        "# Code Review Report\n",
        f"_Generated by git-ai-review on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_\n",
        "",
    ]

    for result in results:
        lines.append(f"## `{result.path}`\n")
        if result.error:
            lines.append(f"> **Error**: {result.error}\n")
        else:
            lines.append(result.review)
        lines.append("\n---\n")

    if output_path.exists():
        console.print(f"[yellow]⚠ File already exists. Overwriting: {output_path}[/yellow]")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
