"""Rich를 이용한 터미널 출력 및 마크다운 저장."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.rule import Rule
from rich.text import Text

from gar.reviewer import ReviewResult

console = Console()


def print_header(title: str = "git-ai-review") -> None:
    console.print(Rule(f"[bold cyan]{title}[/bold cyan]"))


def print_review(result: ReviewResult) -> None:
    """단일 파일 리뷰를 Rich 패널로 출력한다."""
    if result.error:
        console.print(
            Panel(
                Text(f"[오류] {result.error}", style="red"),
                title=f"[bold red]{result.path}[/bold red]",
                border_style="red",
            )
        )
        return

    md = Markdown(result.review)
    console.print(
        Panel(
            md,
            title=f"[bold green]{result.path}[/bold green]",
            border_style="green",
            padding=(1, 2),
        )
    )


def print_all_reviews(results: list[ReviewResult]) -> None:
    print_header()
    console.print(f"[dim]총 {len(results)}개 파일 리뷰[/dim]\n")
    for result in results:
        print_review(result)
        console.print()

    failed = [r for r in results if not r.ok]
    if failed:
        console.print(Rule("[bold red]리뷰 실패 목록[/bold red]"))
        for r in failed:
            console.print(f"[red]✗ {r.path}:[/red] {r.error}")


def save_markdown(results: list[ReviewResult], output_path: Path | None = None) -> Path:
    """리뷰 결과를 마크다운 파일로 저장한다."""
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = Path(f"review_{timestamp}.md")

    lines: list[str] = [
        "# Code Review Report\n",
        f"_Generated by git-ai-review on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_\n",
        "",
    ]

    for result in results:
        lines.append(f"## `{result.path}`\n")
        if result.error:
            lines.append(f"> **오류**: {result.error}\n")
        else:
            lines.append(result.review)
        lines.append("\n---\n")

    if output_path.exists():
        console.print(f"[yellow]⚠ 파일이 이미 존재합니다. 덮어씁니다: {output_path}[/yellow]")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
